### ISSUE TITLE
Unhandled rejection RequestError with rocketChatClient.users.info()

### ISSUE THREAD

**Issue by tim-soft** [qeesung/rocketchat-node#65] opened 2017-07-08 05:54 UTC
It appears that the users.info function winds up throwing an internal lib error when an invalid id/username is submitted as an argument. The callback still returns the error in function(err, body) but ultimately crashes my app.

My workaround is to just catch whatever is thrown internally

```javascript
api.rocketChatClient.users.info(args.id, function(err, body) {
    console.log(JSON.stringify(err, null, 4) + '\n');
    console.log(JSON.stringify(body, null, 4) + '\n');

    if(err) {
        console.log("rejecting...");
        reject(err);
    }

    resolve(body);
}).catch(err => {
    throw (err.statusCode + ": " + err.name);
});
```

Here's the output when entering an invalid id/username:
```
Unhandled rejection RequestError: The required "userId" or "username" param provided does not match any users [error-invalid-user]
    at Request.clientRequest [as _callback] (C:\Users\******\Desktop\ClientPortal-v3\node_modules\rocketchat\lib\net.js:148:38)
    at Request.self.callback (C:\Users\******\Desktop\ClientPortal-v3\node_modules\request\request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\Users\******\Desktop\ClientPortal-v3\node_modules\request\request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (C:\Users\******\Desktop\ClientPortal-v3\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickDomainCallback (internal/process/next_tick.js:198:9)
From previous event:
    at RestClient.request (C:\Users\******\Desktop\ClientPortal-v3\node_modules\rocketchat\lib\net.js:132:16)
    at Users.info (C:\Users\******\Desktop\ClientPortal-v3\node_modules\rocketchat\lib\api\users.js:18:28)
    at Promise (C:\Users\******\Desktop\ClientPortal-v3\src\data\types\RocketChat\GetAllUsers.js:46:1)
    at Promise (<anonymous>)
    at getUser (C:\Users\******\Desktop\ClientPortal-v3\src\data\types\RocketChat\GetAllUsers.js:45:1)
    at rocketChatGetUser (C:\Users\******\Desktop\ClientPortal-v3\src\data\types\RocketChat\GetAllUsers.js:60:1)
    at C:\Users\******\Desktop\ClientPortal-v3\node_modules\graphql-tools\src\schemaGenerator.ts:456:22
    at resolveFieldValueOrError (C:\Users\******\Desktop\ClientPortal-v3\node_modules\graphql\execution\execute.js:498:12)
    at resolveField (C:\Users\******\Desktop\ClientPortal-v3\node_modules\graphql\execution\execute.js:462:16)
    at C:\Users\******\Desktop\ClientPortal-v3\node_modules\graphql\execution\execute.js:311:18
    at Array.reduce (native)
    at executeFields (C:\Users\******\Desktop\ClientPortal-v3\node_modules\graphql\execution\execute.js:308:42)
    at executeOperation (C:\Users\******\Desktop\ClientPortal-v3\node_modules\graphql\execution\execute.js:236:122)
    at executeImpl (C:\Users\******\Desktop\ClientPortal-v3\node_modules\graphql\execution\execute.js:133:26)
    at execute (C:\Users\******\Desktop\ClientPortal-v3\node_modules\graphql\execution\execute.js:102:150)
    at C:\Users\******\Desktop\ClientPortal-v3\node_modules\express-graphql\dist\index.js:166:37
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:208:7)
```

**Comment by qeesung** [comment] 2017-07-08 06:55
You mean even if you caught the exception in the callback function, but the promise still be rejected?

**Comment by MatthiasKainer** [comment] 2017-07-08 07:28
From our side, is 1 or 2 expected?
```
api.rocketChatClient.users.info("invalid user", function(err, body) {
    // 1: fail because error passed
    should(true).be.false();
}).catch(err => {
    // 2. fail because exception thrown
    should(true).be.false();
});
```

**Comment by tim-soft** [comment] 2017-07-08 07:53
From my point of view (end user), the api should return an object with an error message for me to handle in whatever way necessary for the situation

I believe some stuff is thrown and not caught from the lib side, regardless of what I try to catch promise-wise

**Comment by MatthiasKainer** [comment] 2017-07-08 08:11
If the callback is containing the error, but still an exception is thrown, maybe bluebird does something with the exception when calling reject? my inet is too flaky to git pull (in a train), will have to test later. @qeesung are u looking into this as well?

**Comment by qeesung** [comment] 2017-07-08 08:17
@MatthiasKainer Sure, I checked the source code, both callback and promise are supported. When an exception is thrown, the callback will be called with err object and  the returned promise would be rejected.

**Comment by MatthiasKainer** [comment] 2017-07-08 08:39
@tim-soft can you maybe to a pr with a failing test so we know what behavior you exepect to pass and to implement against? thx :)

**Comment by MatthiasKainer** [comment] 2017-07-08 09:55
kk, implemented a test that reproduces the issue on pr #68. Will check how to fix that

**Comment by MatthiasKainer** [comment] 2017-07-08 10:04
here https://travis-ci.org/qeesung/rocketchat-node/jobs/251438601#L1015 you can see the issue - the rejection is considered unhandled.

**Comment by MatthiasKainer** [comment] 2017-07-08 10:50
@tim-soft this is fixed in #65. As soon as @qeesung gives his go and releases a new version, this issue is fixed

**Comment by MatthiasKainer** [comment] 2017-07-08 12:25
@tim-soft use 0.57.1-alpha to have a fix for this issue. Note that version numbers now are in sync with rocket.chat, that's why there is a jump

**Closed by MatthiasKainer** 2017-07-08 12:25 UTC

**Comment by qeesung** [comment] 2017-07-08 12:50
Update version to `0.57.2-alpha`, because the version `0.57.1-alpha` has been published unexpected

**Comment by qeesung** [comment] 2017-07-08 12:52
What a terrible network in China! I can hardly access npmjs 😢
